# Generated by Django 3.1 on 2024-03-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userslistregisters',
            name='password',
            field=models.IntegerField(null=True, verbose_name='Passwords'),
        ),
    ]
