# Generated by Django 3.1 on 2024-04-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20240323_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='userslistregisters',
            name='discription',
            field=models.CharField(default=2323, max_length=250, verbose_name='Name and Surname'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userslistregisters',
            name='photo',
            field=models.ImageField(default=1, upload_to='', verbose_name='Photo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userslistregisters',
            name='name_surname',
            field=models.CharField(max_length=100, verbose_name='Name and Surname'),
        ),
        migrations.AlterField(
            model_name='userslistregisters',
            name='password',
            field=models.CharField(default=1, max_length=50, verbose_name='Passwords'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userslistregisters',
            name='username',
            field=models.CharField(max_length=100, verbose_name='Username'),
        ),
    ]
