# Generated by Django 3.1 on 2024-04-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_auto_20240404_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userslistregisters',
            name='discription',
            field=models.CharField(blank=True, default=1, max_length=250, verbose_name='Discription'),
            preserve_default=False,
        ),
    ]
