# Generated by Django 3.1 on 2024-04-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_auto_20240404_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userslistregisters',
            name='photo',
            field=models.ImageField(upload_to='../../static/blog_app/img/', verbose_name='Photo'),
        ),
    ]
