# Generated by Django 3.1 on 2024-04-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_auto_20240406_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersListPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('photo', models.ImageField(upload_to='blog_app/static/blog_app/img/', verbose_name='Users Photo')),
            ],
            options={
                'verbose_name': 'user_photo',
                'verbose_name_plural': 'user_photos',
            },
        ),
        migrations.AlterField(
            model_name='userslistregisters',
            name='photo',
            field=models.ImageField(upload_to='blog_app/static/blog_app/img/', verbose_name='Photo'),
        ),
    ]
