# Generated by Django 3.1 on 2024-05-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_userslistphoto_id_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userslistphoto',
            name='id_photo',
            field=models.CharField(max_length=100, unique=True, verbose_name='Id Photo'),
        ),
    ]
