# Generated by Django 3.1 on 2024-05-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_auto_20240512_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='userslistphoto',
            name='like',
            field=models.IntegerField(default=1, verbose_name='Like'),
            preserve_default=False,
        ),
    ]
