# Generated by Django 3.1 on 2024-05-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0012_userslistphoto_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikesListPhoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='blog_app/static/blog_app/img/', verbose_name='Users Photo')),
                ('id_photo', models.CharField(max_length=100, unique=True, verbose_name='Id Photo')),
                ('username_liked', models.CharField(max_length=100, verbose_name='Username')),
            ],
            options={
                'verbose_name': 'like_photo',
                'verbose_name_plural': 'like_photos',
            },
        ),
    ]
