# Generated by Django 3.1 on 2024-05-23 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0013_likeslistphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeslistphoto',
            name='photo',
        ),
    ]
