# Generated by Django 3.1 on 2024-06-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0015_auto_20240523_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentListPhoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_photo', models.CharField(max_length=100, verbose_name='Id Photo')),
                ('username_comment', models.CharField(max_length=100, verbose_name='Username')),
                ('comment', models.CharField(max_length=250, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'comment_photo',
                'verbose_name_plural': 'comment_photos',
            },
        ),
    ]
