# Generated by Django 3.1 on 2024-06-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0016_commentlistphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='userslistregisters',
            name='csrftoken',
            field=models.CharField(blank=True, max_length=250, verbose_name='Token'),
        ),
    ]
