# Generated by Django 3.1 on 2024-06-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0017_userslistregisters_csrftoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersListTopics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name Topics')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('photo', models.ImageField(blank=True, upload_to='blog_app/static/blog_app/img/', verbose_name='Users Photo')),
                ('id_topics', models.CharField(max_length=100, unique=True, verbose_name='Id Photo')),
            ],
            options={
                'verbose_name': 'user_topic',
                'verbose_name_plural': 'user_topics',
            },
        ),
        migrations.AlterField(
            model_name='userslistphoto',
            name='like',
            field=models.IntegerField(default=0, verbose_name='Like'),
        ),
    ]
