# Generated by Django 3.1 on 2024-07-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0018_auto_20240630_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='userslisttopics',
            name='discription',
            field=models.CharField(blank=True, max_length=10000, verbose_name='Discription'),
        ),
    ]
