# Generated by Django 3.1 on 2024-07-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0019_userslisttopics_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userslisttopics',
            name='id_topics',
            field=models.CharField(max_length=100, unique=True, verbose_name='Id Topics'),
        ),
    ]
