# Generated by Django 3.1 on 2024-07-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0020_auto_20240706_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userslisttopics',
            name='discription',
            field=models.CharField(max_length=10000, verbose_name='Discription'),
        ),
    ]
