# Generated by Django 3.1 on 2024-07-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0021_auto_20240707_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentListTopics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_topics', models.CharField(max_length=100, verbose_name='Id Topic')),
                ('username_comment', models.CharField(max_length=100, verbose_name='Username')),
                ('comment', models.CharField(max_length=250, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'comment_topic',
                'verbose_name_plural': 'comment_topics',
            },
        ),
    ]
