# Generated by Django 3.1 on 2024-08-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0022_commentlisttopics'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersChat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_chat', models.CharField(max_length=200, verbose_name='Id Chat')),
                ('name_chat', models.CharField(max_length=100, verbose_name='Name Chat')),
                ('notice_user1', models.CharField(blank=True, max_length=1000000, verbose_name='Notice User First')),
                ('notice_user2', models.CharField(blank=True, max_length=1000000, verbose_name='Notice User Second')),
                ('csrftoken_user1', models.CharField(max_length=50, verbose_name='Token User First')),
                ('csrftoken_user2', models.CharField(max_length=50, verbose_name='Token User Second')),
            ],
            options={
                'verbose_name': 'chat',
                'verbose_name_plural': 'chats',
            },
        ),
    ]
