# Generated by Django 3.1 on 2024-08-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0023_userschat'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesChat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_chat', models.CharField(max_length=200, verbose_name='Id Chat')),
                ('name_chat', models.CharField(max_length=100, verbose_name='Name Chat')),
                ('notice_user', models.CharField(blank=True, max_length=1000000, verbose_name='Notice User')),
                ('csrftoken_user', models.CharField(max_length=50, verbose_name='Token User')),
            ],
            options={
                'verbose_name': 'chat',
                'verbose_name_plural': 'chats',
            },
        ),
    ]
