# Generated by Django 3.1 on 2024-08-17 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0024_noteschat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noteschat',
            options={'verbose_name': 'notes chat', 'verbose_name_plural': 'notes chats'},
        ),
    ]
