# Generated by Django 3.1 on 2024-08-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0025_auto_20240817_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteschat',
            name='csrftoken_user',
            field=models.CharField(max_length=100, unique=True, verbose_name='Token User'),
        ),
        migrations.AlterField(
            model_name='noteschat',
            name='id_chat',
            field=models.CharField(max_length=200, unique=True, verbose_name='Id Chat'),
        ),
        migrations.AlterField(
            model_name='userschat',
            name='id_chat',
            field=models.CharField(max_length=200, unique=True, verbose_name='Id Chat'),
        ),
    ]
