# Generated by Django 3.1 on 2024-08-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0027_auto_20240818_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteschat',
            name='csrftoken_user',
            field=models.CharField(max_length=100, unique=True, verbose_name='Token User'),
        ),
    ]
