# Generated by Django 3.1 on 2024-08-22 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0031_auto_20240819_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noteschat',
            old_name='csrftoken_user',
            new_name='username_user',
        ),
        migrations.RenameField(
            model_name='userschat',
            old_name='csrftoken_user1',
            new_name='username_user1',
        ),
        migrations.RenameField(
            model_name='userschat',
            old_name='csrftoken_user2',
            new_name='username_user2',
        ),
    ]
