# Generated by Django 3.1 on 2024-08-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0033_auto_20240822_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='userschat',
            name='photo_chat_user1',
            field=models.ImageField(blank=True, upload_to='blog_app/static/blog_app/img/', verbose_name='Photo User Chat First'),
        ),
        migrations.AddField(
            model_name='userschat',
            name='photo_chat_user2',
            field=models.ImageField(blank=True, upload_to='blog_app/static/blog_app/img/', verbose_name='Photo User Chat Second'),
        ),
    ]
