# Generated by Django 3.1 on 2024-08-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0036_auto_20240826_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userschat',
            name='name_chat_user1',
            field=models.CharField(max_length=100, verbose_name='Name Chat User First'),
        ),
        migrations.AlterField(
            model_name='userschat',
            name='name_chat_user2',
            field=models.CharField(max_length=100, verbose_name='Name Chat User Second'),
        ),
    ]
