# Generated by Django 3.1 on 2024-09-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0041_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.CharField(max_length=100, verbose_name='Users'),
        ),
    ]
