# Generated by Django 3.1 on 2024-09-05 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0042_auto_20240905_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'notification', 'verbose_name_plural': 'notifications'},
        ),
    ]
