# Generated by Django 3.1 on 2024-09-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0043_auto_20240905_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='owner',
            field=models.CharField(default='sdknksd', max_length=100, verbose_name='Owner'),
            preserve_default=False,
        ),
    ]
