# Generated by Django 3.1 on 2024-09-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0044_notification_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersListPhotoGallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('photo', models.ImageField(upload_to='blog_app/static/blog_app/img/', verbose_name='Users Photo')),
                ('id_photo', models.CharField(max_length=100, unique=True, verbose_name='Id Photo')),
                ('tag', models.CharField(max_length=100, verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'user_photo',
                'verbose_name_plural': 'user_photos',
            },
        ),
    ]
