# Generated by Django 3.1 on 2024-09-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0045_userslistphotogallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userslistphotogallery',
            name='tag',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tag'),
        ),
    ]
