# Generated by Django 3.1 on 2024-09-10 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0046_auto_20240910_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userslistphotogallery',
            options={'verbose_name': 'user_photo_gallery', 'verbose_name_plural': 'user_photos_gallery'},
        ),
    ]
